// Sample notification dataset for the panel.
// Types map to icon + tile color + accent treatment.
// `read` controls the unread dot + section sort.
window.NOTIF_DATA = [
  {
    id: "n1",
    type: "sales-drop",
    title: "Caída de ventas: 100%",
    body: "Las ventas de esta semana ($0.00) cayeron 100% vs el promedio semanal ($112.50).",
    age: "4 días",
    read: false,
  },
  {
    id: "n2",
    type: "sales-drop",
    title: "Caída de ventas: 89%",
    body: "Las ventas de esta semana ($450.00) cayeron 89% vs el promedio semanal ($4,045.75).",
    age: "11 días",
    read: false,
  },
  {
    id: "n3",
    type: "purchase",
    person: { initial: "AN", name: "Ana Narvaez", color: "#C73E73" },
    branch: "Matriz",
    title: "Compró $250.00",
    body: "Ganó 124 puntos",
    age: "17 días",
    read: false,
  },
  {
    id: "n4",
    type: "purchase",
    person: { initial: "AN", name: "Ana Narvaez", color: "#C73E73" },
    branch: "Matriz",
    title: "Compró $200.00",
    body: "Ganó 99 puntos",
    age: "17 días",
    read: false,
  },
  {
    id: "n5",
    type: "review",
    person: { initial: "AN", name: "Ana", color: "#E8843C" },
    branch: "Matriz",
    title: "Nueva reseña",
    rating: 5,
    body: "\"Buen servicio, gracias\"",
    age: "23 días",
    read: false,
  },
  {
    id: "n6",
    type: "reward-pending",
    person: { initial: "AN", name: "Ana Narvaez", color: "#C73E73" },
    title: "Recompensa por entregar",
    body: "Canjeó sus puntos por: Camisetas",
    age: "27 días",
    read: true,
  },
  {
    id: "n7",
    type: "low-stock",
    productImg: null,
    title: "¡Stock bajo! Quedan 4",
    body: "La recompensa \"Camisetas\" se está agotando.",
    age: "27 días",
    read: true,
  },
  {
    id: "n8",
    type: "reward-delivered",
    person: { initial: "AN", name: "Ana Narvaez", color: "#C73E73" },
    branch: "Matriz",
    title: "Recompensa entregada",
    body: "Se entregó: Camisetas",
    age: "27 días",
    read: true,
  },
];

window.NOTIF_TYPE_META = {
  "sales-drop":       { icon: "chart-up",     tile: "#0E1F5C", badge: null,             tone: "alert"   },
  "purchase":         { icon: "coin",         tile: "#F58220", badge: "coin",           tone: "good"    },
  "review":           { icon: "star",         tile: "#E8843C", badge: "star",           tone: "good"    },
  "reward-pending":   { icon: "gift",         tile: "#2244C8", badge: "clock",          tone: "info"    },
  "reward-delivered": { icon: "check-circle", tile: "#2D9C5F", badge: "check",          tone: "good"    },
  "low-stock":        { icon: "warning",      tile: "#DC3545", badge: "warning",        tone: "warn"    },
};
